# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'channel_info.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1365, 850)
        self.channel_name_label = QtWidgets.QLabel(Form)
        self.channel_name_label.setGeometry(QtCore.QRect(500, 20, 231, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.channel_name_label.setFont(font)
        self.channel_name_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.channel_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.channel_name_label.setObjectName("channel_name_label")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-10, 80, 621, 431))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(50, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.active_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.active_label.setObjectName("active_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.active_label)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.channel_id_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.channel_id_label.setObjectName("channel_id_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.channel_id_label)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.capacity_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.capacity_label.setObjectName("capacity_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.capacity_label)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.local_balance_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.local_balance_label.setObjectName("local_balance_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.local_balance_label)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.remote_balance_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.remote_balance_label.setObjectName("remote_balance_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.remote_balance_label)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.commit_fee_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.commit_fee_label.setObjectName("commit_fee_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.commit_fee_label)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.commit_weight_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.commit_weight_label.setObjectName("commit_weight_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.commit_weight_label)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.fee_per_kw_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.fee_per_kw_label.setObjectName("fee_per_kw_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fee_per_kw_label)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(610, 80, 621, 431))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(50, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.unsettled_balance_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.unsettled_balance_label.setObjectName("unsettled_balance_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.unsettled_balance_label)
        self.tot_sat_sent_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.tot_sat_sent_label.setObjectName("tot_sat_sent_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tot_sat_sent_label)
        self.tot_sat_received_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.tot_sat_received_label.setObjectName("tot_sat_received_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tot_sat_received_label)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.num_updates_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.num_updates_label.setObjectName("num_updates_label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.num_updates_label)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.pending_htlcs_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.pending_htlcs_label.setObjectName("pending_htlcs_label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pending_htlcs_label)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.csv_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.csv_label.setObjectName("csv_label")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.csv_label)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.private_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.private_label.setObjectName("private_label")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.private_label)
        self.formLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(-20, 510, 1251, 91))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(50, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.channel_point_label = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.channel_point_label.setFont(font)
        self.channel_point_label.setObjectName("channel_point_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.channel_point_label)
        self.remote_pubkey_label = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.remote_pubkey_label.setFont(font)
        self.remote_pubkey_label.setObjectName("remote_pubkey_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.remote_pubkey_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.channel_name_label.setText(_translate("Form", "TextLabel"))
        self.label.setText(_translate("Form", "Active:"))
        self.active_label.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "Channel id:"))
        self.channel_id_label.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "Capacity:"))
        self.capacity_label.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "Local balance:"))
        self.local_balance_label.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "Remote balance:"))
        self.remote_balance_label.setText(_translate("Form", "TextLabel"))
        self.label_15.setText(_translate("Form", "Commit fee:"))
        self.commit_fee_label.setText(_translate("Form", "TextLabel"))
        self.label_16.setText(_translate("Form", "Commit weight:"))
        self.commit_weight_label.setText(_translate("Form", "TextLabel"))
        self.label_17.setText(_translate("Form", "Fee per kw:"))
        self.fee_per_kw_label.setText(_translate("Form", "TextLabel"))
        self.label_18.setText(_translate("Form", "Unsettled balance:"))
        self.label_19.setText(_translate("Form", "Total satoshis sent:"))
        self.unsettled_balance_label.setText(_translate("Form", "TextLabel"))
        self.tot_sat_sent_label.setText(_translate("Form", "TextLabel"))
        self.tot_sat_received_label.setText(_translate("Form", "TextLabel"))
        self.label_20.setText(_translate("Form", "Total satoshis received:"))
        self.label_21.setText(_translate("Form", "Number of updates:"))
        self.num_updates_label.setText(_translate("Form", "TextLabel"))
        self.label_29.setText(_translate("Form", "Pending htlcs"))
        self.pending_htlcs_label.setText(_translate("Form", "TextLabel"))
        self.label_31.setText(_translate("Form", "CSV delay"))
        self.csv_label.setText(_translate("Form", "TextLabel"))
        self.label_33.setText(_translate("Form", "Private"))
        self.private_label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "Remote pubkey:"))
        self.label_3.setText(_translate("Form", "Channel point:"))
        self.channel_point_label.setText(_translate("Form", "TextLabel"))
        self.remote_pubkey_label.setText(_translate("Form", "TextLabel"))

